# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Eric Tendian
description: "Eric Tendian is a student entrepreneur utilizing technology to improve education for fellow college students. Currently co-founder of Clarify and software engineer at Packback. Majoring in ITM at IIT."
url: https://tendian.io
baseurl: ""

google_analytics: UA-30674963-4

# Author settings
author:
  name      : Eric Tendian
  job       : "Full-Stack Web&nbsp;Developer"
  bio       : "Fearlessly &amp; relentlessly curious. Software engineer at <a href='https://packbackbooks.com/' target='_blank'>Packback</a>. Student at <a href='https://web.iit.edu/' target='_blank'>Illinois Tech</a>. Nothing is impossible."
  thumb     : /images/author.png
  email     : eric@tendian.io
  url       : https://tendian.io
  blogurl   : "https://eric.tendian.io"
  github    : https://github.com/EricTendian
  twitter   : https://twitter.com/EricTendian
  facebook  : https://facebook.com/BinarySentinel
  linkedin  : https://linkedin.com/in/erictendian

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: resume
    title: Resume
