# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Eric Tendian
description: "Eric Tendian is a Principal Engineer at Packback, is a full-stack engineer and entrepreneur with a passion for using technology to transform education. Also reports Chicago breaking news on Twitter."
url: https://tendian.io
baseurl: ""

google_analytics: UA-30674963-4

# Author settings
author:
  name      : Eric Tendian
  job       : "Full-Stack Engineer"
  bio       : "Fearlessly &amp; relentlessly curious. Principal Engineer at <a href='https://www.packback.co/' target='_blank'>Packback</a>. Founder of <a href='https://crimeisdown.com/' target='_blank'>CrimeIsDown.com</a>. Nothing is impossible."
  thumb     : /images/author.png
  email     : eric@tendian.io
  url       : https://tendian.io
  blogurl   : "https://eric.tendian.io"
  github    : https://github.com/EricTendian
  twitter   : https://twitter.com/EricTendian
  facebook  : https://facebook.com/BinarySentinel
  linkedin  : https://linkedin.com/in/erictendian

# navbar pages
navbar:
  - slug: about
    title: About
#  - slug: resume
#    title: Resume
